### PR TITLE
fix numpy versiom for compatibility with pymc

### PR DESCRIPTION
**Pull request by clementhelsens**
Hi Davide, 

as discussed we need a specific version of numpy to work with pymc 2.3
I haven't tried to remove the ==2.3 for pymc, but this setup seems to work well for me.
We will see it in the travis test I guess!

Clement

### CODE REVIEW

**Comment by gerbaudo** [comment]
Hi @clementhelsens 
Thank you for the pull request.
Can you try updating the travis.yml as indicated here, please?
https://conda.io/docs/travis.html
(please note the `if 2.7` section). I suspect the line with `wget ... Miniconda...` should have a `2` instead of a `3` and the `conda` lines `config` + `update` should be like in the example above.

**Comment by gerbaudo** [comment]
P.S. If you're busy I can also take a look, but probably I'll get to this only next week.

**Comment by clementhelsens** [comment]
Hello @gerbaudo, 
That's working now. I had to change the numpy version in the travis test as it is not using the same version as the setup.py

Cheers,
Clement

**Comment by gerbaudo** [comment]
Hi @clementhelsens 
thank you for the fix, now merged!

**Comment by clementhelsens** [comment]
thanks!
@francescorubbo , could you now make a new tag for the pip installation of pyfbu?

**Comment by francescorubbo** [comment]
Hi @clementhelsens, done. It should be fbu-0.0.3.dev5

**Pull request merged**
