### PR TITLE
Py3mig

### PR DESCRIPTION
**Pull request by francescorubbo**
Migration to Python 3 and PyMC3.
A few things are still missing:
   * implement knobs to tune MCMC sampling
   * implement tests for regularization
   * update travis configuration
   * update documentation

### CODE REVIEW

**Comment by clementhelsens** [comment]
Hello both, 

after checking the code and the results with an ongoing analyse, the results are ok.
I suggest we proceed with merging and tagging a new version so that it can be installed with pip.
In the mean time I will slowly start again the documentation, but I'm not optimistic if I'll be able to complete all the notebooks.

Cheers,
Clement

**Comment by francescorubbo** [comment]
Hi Clement,

Thanks for keeping things moving!
I plan to look at this during the weekend.
Before merging, at the very least we need to have the updated travis configuration in place.
Hopefully it won't take long.

Francesco

**Comment by gerbaudo** [comment]
Hi!
Yes I do still get the notifications.
However I am afraid I won't have any time to work on FBI in the coming
weeks...sorry.

**Comment by clementhelsens** [comment]
Hello both, 
any idea Francesco when you will be able to update the travis?
thanks,Clement

**Comment by francescorubbo** [comment]
Hi Clement,

Thanks for the reminder, I completely forgot about this...
I've updated the Travis configuration and did some cleanup.
I think we are ready to merge into the master and distribute, provided we update a bit the documentation. 
If you get a chance to help there, it'd be great, otherwise I'll work on some time in the next few days.

**Comment by clementhelsens** [comment]
Hi Francesco, 

great, thanks!
Why are some of the tests not successful?
For the documentation, yes I can do a lot there.
I just have also to finalize the FCC CDR which takes me some time and I'm leaving for the ATLAS week in Tokyo this Friday, so not sure what can be done before that but I'll try.
Do you get an idea of the level of documentation we need?
If you start something let me know what you do so that we don't have overlaps.
Cheers,Clement

Cheers,
Clement

**Comment by francescorubbo** [comment]
Somehow one of the tests got stuck..I restarted it and now it's fine.
I'm mainly talking about the technical documentation (README, notebook) that goes with the package. I should be able to work on it this week.

**Comment by clementhelsens** [comment]
Ok, great!
Shall we merge this PR and open a new one for the documentation?
Like this you could also proceed with putting the new version in pypi?

**Pull request merged**
