### PR TITLE
Updatedocs

### PR DESCRIPTION
**Pull request by francescorubbo**
Updated documentation to reflect latest changes.
Note that I removed the Regularization section from the example in the jupyter notebook.
If anybody has time to look into that (and write a test for it!), it'd be great.

Once we are happy to merge this, we can tag and upload v0.0.3 in PyPI.

### CODE REVIEW

**Comment by demarley** [comment]
@francescorubbo is there something wrong with the regularization now that PyMC3 is used?

**Comment by francescorubbo** [comment]
It’s just that I haven’t gotten a chance to migrate that part of the code. I would like to rethink a bit the way it’s implemented. Maybe I’ll give it a try tomorrow but maybe in the meantime we should go ahead uploading on PyPI the current version?

**Comment by francescorubbo** [comment]
@clementhelsens @demarley : fbu-0.1.0 is up! Let me know if you get a chance to test things out.

**Comment by demarley** [comment]
@francescorubbo I was able to test the latest version from pip and everything ran as expected.  I tested the old regularization example just to see what would happen, and it did break [1]. 
Besides that, everything seems okay from the basic tests.   
Doing more now -- I will open a new issue if something happens.

[1] 
```python
>>> myfbu.regularization = Regularization('Tikhonov',parameters=[{'refcurv':0.,'alpha':0.1}])
>>> myfbu.run()


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-0be02e1f6cf9> in <module>()
----> 1 myfbu.run()

/Users/demarley/anaconda2/lib/python2.7/site-packages/fbu/PyFBU.pyc in run(self)
    113         # define potential to constrain truth spectrum
    114             if self.regularization:
--> 115                 truthpot = self.regularization.getpotential(truth)
    116 
    117         #This is where the FBU method is actually implemented

/Users/demarley/anaconda2/lib/python2.7/site-packages/fbu/Regularization.pyc in getpotential(self, truth)
     23 
     24     def getpotential(self,truth):
---> 25         ntotbins = len(truth)
     26         step = ntotbins/self.ndiffbins
     27         edges = [(ii,ii+step) for ii in range(0,ntotbins,step)]

TypeError: object of type 'TensorVariable' has no len()
```

**Pull request merged**
